# REST-API SERVER SPECIFIC CONSTANTS
RUN_API_TEST = False
LOCAL_SERVICE_PORT = 8080
URL = 'http://localhost:{0}'.format(LOCAL_SERVICE_PORT)
URL_PATTERN_SERVICED = ('/(.*)', 'RestAPIServer')
SERVER_ALIVE_FOR_SECONDS = -120  # Use negative value for infinite life
TIME_IN_SEC_BETWEEN_HEARTBEATS = 5
HEARTBEATS_SKIPPED_BEFORE_REAPING = 2

# SCANNER SPECIFIC CONSTANTS
SERVER_IP = "172.24.22.113"
SERVER_PORT = 8080
RUN_BASIC_TEST = False
ICMP_REACHABLE_TYPE = ["echo-reply"]
SERVER_URL = 'http://{0}:{1}'.format(SERVER_IP, SERVER_PORT)
MAX_THREADS = 500