# REST-API SERVER SPECIFIC CONSTANTS
RUN_API_TEST = False
SERVICE_PORT = '8080'
URL = 'http://localhost:' + SERVICE_PORT
URL_PATTERN_SERVICED = ('/(.*)', 'RestAPIServer')
SERVER_ALIVE_FOR_SECONDS = -120  # Use negative value for infinite life

# SCANNER SPECIFIC CONSTANTS
RUN_BASIC_TEST = True
ICMP_REACHABLE_TYPE = ["echo-reply"]
SERVER_URL = 'http://172.24.22.113:8080'